# Model arguments
model_name_or_path: aisingapore/sea-lion-7b
model_revision: main
torch_dtype: float16
trust_remote_code: true

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 256
lora_alpha: 512
lora_dropout: 0.05
lora_target_modules:
  - Wqkv
  - up_proj
  - out_proj
  - down_proj

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '### USER:\n' + message['content'] }}\n\n{% elif message['role'] == 'assistant' %}\n{{ '### RESPONSE:\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '### RESPONSE:' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  /root/flan_dataset/flan_v1: 0.00001
dataset_splits:
  - train
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: steps
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: zephyr-7b-sft-qlora
# hub_strategy: every_save
learning_rate: 2.0e-04
log_level: info
logging_steps: 500
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: /workspace/alignment-handbook_old/data/sealion-7b-sft-qlora-v1
overwrite_output_dir: true
per_device_eval_batch_size: 5
per_device_train_batch_size: 5
push_to_hub: false
report_to:
  - wandb
save_strategy: "steps"
save_steps: 5000
save_total_limit: 4
seed: 42
warmup_ratio: 0.1
