# Model arguments
model_name_or_path: aisingapore/sea-lion-7b
tokenizer_name_or_path: aisingapore/sea-lion-7b
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: false
trust_remote_code: true

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '### USER:\n' + message['content'] }}\n\n{% elif message['role'] == 'assistant' %}\n{{ '### RESPONSE:\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '### RESPONSE:' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  /root/flan_dataset/flan_v1: 1 # size of dataset (fraction of full dataset
dataset_splits:
  - train
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: false
# evaluation_strategy: epoch
gradient_accumulation_steps: 5
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-05
log_level: info
logging_steps: 20
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 2
output_dir: /workspace/alignment-handbook_old/data/sealion-7b-sft-full-v1
overwrite_output_dir: true
per_device_eval_batch_size: 5
per_device_train_batch_size: 5
push_to_hub: false
remove_unused_columns: true
report_to:
  - wandb
save_strategy: "epoch"
# save_steps: 1000
# save_total_limit: 1
seed: 42
warmup_ratio: 0.1
