# Model arguments
model_name_or_path: /workspace/dpo_test/final_checkpoint
torch_dtype: bfloat16

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 128
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- Wqkv
- up_proj
- out_proj
- down_proj

# Data training arguments

dataset_mixer:
  /workspace/dpo_test/scripts/responses_ranking.jsonl: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 4

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: false
save_strategy: epoch
#eval_steps: 100
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
#hub_model_id: zephyr-7b-dpo-qlora
learning_rate: 5.0e-7
log_level: info
logging_steps: 30
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 512
num_train_epochs: 6
optim: paged_adamw_32bit
output_dir: data/sealion-7b-dpo-qlora-V1 # It is handy to append `hub_model_revision` to keep track of your local experiments
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
# save_steps: 100
# save_total_limit: 1
seed: 42
warmup_ratio: 0.1
